site_name: SeaTable Developer Manual
site_url: https://developer.seatable.com/
site_author: SeaTable GmbH
site_description: >-
  Official SeaTable Developer Manual.

# Repository
repo_name: seatable/seatable-developer-docs
repo_url: https://github.com/seatable/seatable-developer-docs/

# Copyright
copyright: Copyright &copy; 2022 - 2025 SeaTable GmbH

# Configuration
theme:
  name: material
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.sections # top-level sections are rendered as groups in the sidebar for viewports above 1220px
    - navigation.indexes # documents can be directly attached to sections
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate # offer a comfortable and friendly way to attach arbitrary content to specific sections of code
  custom_dir: overrides

  # icon & favicon
  logo: media/SeaTable256-256.png
  favicon: media/seatable-favicon.ico

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized
  - include-markdown:
      rewrite_relative_urls: false
  #- redirects:
  #    redirect_maps:
  #      'changelog/server-changelog.md': 'https://seatable.com/changelog/'
  #      'changelog/changelog-for-seatable-professional-server.md': 'https://seatable.com/changelog/'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seatable/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/seatable/seatable-enterprise
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/seatable/
  status:
    new: requires Enterprise Edition
  analytics:
    #provider: matomo
    #site_id: 2
    #provider_url: https://wp-stats.seatable.io/
    
    provider: posthog
    posthog_api_key: phc_wRHcvnLs4nsJLtycPXwtckL4NahZSAlw2uV3d4dm4hT
    posthog_api_host: https://ph.seatable.com
    posthog_ui_host: https://ph.seatable.com

extra_css:
  - stylesheets/extra.css

# Extensions: https://squidfunk.github.io/mkdocs-material/reference/
# PyMdown Extension: https://facelessuser.github.io/pymdown-extensions/extensions/

validation:
  links:
    absolute_links: ignore

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      guess_lang: true
  - pymdownx.details # creates collapsible elements that hide their content
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences: # allows 1) nesting of fences 2) custom fences 3) disable indented code
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys # make entering and styling keyboard key presses easier
  - pymdownx.tabbed: # provides a syntax to easily add tabbed Markdown content
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction:
      - index.md
      - Get support: introduction/get_support.md
  - Python:
      - Getting Started: python/getting-started/index.md
      - Objects & Methods:
          - python/objects/index.md
          - Metadata: python/objects/metadata.md
          - Context: python/objects/context.md
          - Tables: python/objects/tables.md
          - Views: python/objects/views.md
          - Columns: python/objects/columns.md
          - Rows: python/objects/rows.md
          - Links: python/objects/links.md
          - Files: python/objects/files.md
          - Big data: python/objects/big_data.md
          - Accounts: python/objects/accounts.md
          - Users: python/objects/users.md
          - Date utilities: python/objects/date-utils.md
          - Communication utilities: python/objects/communication-utils.md
      - Query with SQL:
          - Introduction: python/sql/introduction.md
          - SQL function reference: python/sql/functions.md
  - JavaScript:
      - javascript/index.md
      - Scripting API:
          - javascript/scripting/index.md
          - Tables: javascript/scripting/tables.md
          - Views: javascript/scripting/views.md
          - Columns: javascript/scripting/columns.md
          - Rows: javascript/scripting/rows.md
          - Links: javascript/scripting/links.md
          - Context: javascript/scripting/context.md
          - Utilities: javascript/scripting/utilities.md
          - Output: javascript/scripting/output.md
      - Client API:
          - Introduction: javascript/client/javascript_api.md
          - Objects & Methods:
              - Metadata: javascript/client/metadata.md
              - Tables: javascript/client/tables.md
              - Views: javascript/client/views.md
              - Columns: javascript/client/columns.md
              - Rows: javascript/client/rows.md
              - Links: javascript/client/links.md
              - SQL: javascript/client/sql_query.md
              - Constants: javascript/client/constants.md
          - Examples:
              - File Upload: javascript/client/examples/file-upload.md
  - PHP: php/index.md
  - Ruby: ruby/index.md
  - Plugin Development:
      - plugins/index.md
      - Environments: plugins/environments.md
      - Available methods: plugins/methods.md
